data_dir = "data"
host_file = f"{data_dir}/host.json"
keys_file = f"{data_dir}/keys.json"
cert_file = f"{data_dir}/cert.json"
token_file = f"{data_dir}/token.json"
root_pubkey_file = f"{data_dir}/root_pubkey.json"
download_dir = "downloads"
