[tool.poetry]
name = "hsecrypto"
version = "0.2.1"
description = ""
authors = ["Morzan6 <morzann09@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
