name: Client tests

on:
  push:
    paths:
        - client/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          cd client/
          python -m pytest tests/tests.py