name: Python lib

on:
    push:
    # pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Python 3.13
              uses: actions/setup-python@v3
              with:
                python-version: "3.13"
            - name: Build crypto lib
              run: |
                python -m pip install --upgrade pip
                cd /home/runner/work/hse_dsa/hse_dsa/crypto
                export POETRY_HOME=/opt/poetry
                python3 -m venv $POETRY_HOME
                $POETRY_HOME/bin/pip install poetry
                $POETRY_HOME/bin/poetry --version
                $POETRY_HOME/bin/poetry build
                TAG=$($POETRY_HOME/bin/poetry version)
                echo "TAG=$TAG" >> $GITHUB_ENV
                git tag "$TAG"
            - name: Creste release
              id: create_release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "/home/runner/work/hse_dsa/hse_dsa/crypto/dist/hsecrypto-0.1.0-py3-none-any.whl"
                bodyFile: "/home/runner/work/hse_dsa/hse_dsa/crypto/README.md"
                name: DSA Crypto lib
                tag: ${{ env.TAG }}
