name: Python lib

on:
    push:
      branches:
        - main
      paths:
        - crypto/**
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Python 3.13
              uses: actions/setup-python@v3
              with:
                python-version: "3.13"
            - name: Build crypto lib
              run: |
                python -m pip install --upgrade pip
                python -m pip install Sphinx
                cd /home/runner/work/hse_dsa/hse_dsa/docs
                chmod +x generate.sh
                ./generate.sh
                
