name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst_parser
          export POETRY_HOME=/opt/poetry
          python -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry
          cd server
          $POETRY_HOME/bin/poetry export --without-hashes --format=requirements.txt > requirements.txt
          pip install -r requirements.txt
          cd ..
          pip install https://github.com/DjamikTea/hse_dsa/releases/download/0.1.1/hsecrypto-0.1.1-py3-none-any.whl
          cd client
          $POETRY_HOME/bin/poetry export --without-hashes --format=requirements.txt > requirements.txt
          pip install -r requirements.txt
          cd ..


      - name: Generate Sphinx documentation
        run: |
          cd docs
          bash generate.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/build/html
