# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths:
        - server/**
  pull_request:
    paths:
        - server/**

permissions:
  contents: read
env:
  DB_HOST: 127.0.0.1
  DB_NAME: hse
  DB_PASSWORD: qwerty352
  DB_PORT: 3306
  DB_USER: root
  TELEGRAM_GATEWAY_API_TOKEN: IWANNAXXXXXXX
  TELEGRAM_TEST_PHONE: 79999999999
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 poetry 
        cd /home/runner/work/hse_dsa/hse_dsa/server
        poetry install
    - name: Setup mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: qwerty352
        mysql database: hse
        mysql user: test
        mysql password: qwerty1234
    - name: sleep
      run: |
        sleep 20
    - name: Test with coverage
      run: |
        poetry run coverage run -m pytest /home/runner/work/hse_dsa/hse_dsa/server/tests/test_main.py
        poetry run coverage report -m
        echo '## Отчет покрытия' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        poetry run coverage report -m >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
